- hosts: all
  remote_user: vagrant
  become: yes
  tasks:
          - name: Instalando o Htop
            apt:
                    name: htop
                    state: present
          - name: Criando o usuario analista
            user:
                    name: analista
                    state: present
          - name: Ajustando o Timezone do Servidor
            timezone:
                    name: America/Sao_Paulo
